name: Rust CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true

    - name: Update Linux
      run: sudo apt update 

    - name: Update Rust
      run: make install

    - name: Check Rust versions
      run: make rust-version

    - name: build Rust
      run: make release

    - name: Format code
      run: make format

    - name: Lint code
      run: make lint

    - name: Create AutoDB table
      run: make create-table

    - name: Insert data into AutoDB
      run: make create

    ## CRUD 
    - name: Create 
      run: make create 
    
    - name: Read
      run: make read 
    
    - name: Update 
      run: make update 
   
    - name: Delete 
      run: make delete

    - name: Run tests
      run: make test

    - name: Pull latest changes
      run: git pull
      
    # Set up Git authentication using PAT
    # - name: Set up Git authentication
    #   run: |
    #     git config --global user.name "GitHub Actions"
    #     git config --global user.email "actions@github.com"
    #     git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/yabeizeng1121/Mini8.git

    - name: Archive Binary
      uses: actions/upload-artifact@v2
      with:
        name: optimized-binary
        path: target/release/invidivual_project_kelly_rust
          
    - name: Generate and push logs
      run: make generate_and_push
